[package]
name = "dynfmt"
version = "0.1.0"
edition = "2024"

[features]
default = ["chrono"]

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
chrono = { version = "0.4.42", features = ["unstable-locales"], optional = true }
log = "0.4.29"
regex = "1.12.2"
